config/routes.rb
Rails.application.routes.draw do
  get "about", to: "about#index", as: "about"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  delete "logout", to: "sessions#destroy"

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# email:string
# password_digest:string

# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
	# Ruby inbuilt function
	# Compares password & password_confirmation
	# hashes it with bcrypt
	has_secure_password

	validates :email, uniqueness: true, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid email address!" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		if session[:user_id]
			@user = User.find_by(id: session[:user_id])
			flash.now[:notice] = "Logged in Successfully!"
		else
			flash.now[:alert] = "Not Logged in!"
		end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		# params -> has data from forms and route parameters
		@user = User.new(user_params)

		if @user.save
			# setting up cookies for login
			session[:user_id] = @user.id
			redirect_to root_path, notice: "Successfullt created account!"
		else
			render :new
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: "Logged out!"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
	<h1>Welcome to Scheduled Tweets!</h1>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info mt-4" role="alert">
		<%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-warning mt-4" role="alert">
		<%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Scheduled Tweets" , root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav my-2 my-lg-0 d-flex align-items-center">
        <% if @user && @user.email %>
          <b-avatar class="text-light" size="4em"><%= @user.email %></b-avatar>
          <%= button_to "logout", logout_path, method: :delete, class: "btn btn-danger mx-md-4" %>
        <% else %>
          <a class="link-light mx-sm-2" href="/login" >Login</a>
          <a class="link-light mx-sm-2" href="/sign_up" >Signup</a>
        <% end %>
      </ul>
    </div>
  </div>
</nav>